- name: Checkmarx AST Scan
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@3bbaca0807ff5abd587965391138479c23b7b369
  uses: Checkmarx/ast-github-action@2.0.18
  with:
    # Provide the AST portal URL
    base_uri: https://eu.ast.checkmarx.net
    # Provide the Tenant for AST portal URL
    cx_tenant: yalin_demo
    # Client ID for AST portal authentication
    cx_client_id: ${{ secrets.CLIENT_ID }}
    # Secret key for AST portal authentication
    cx_client_secret: ${{ secrets.SECRET }}
    # Select a Checkmarx Project Name
    project_name: # optional, default is ${{ github.repository }}
    # Branch name
    branch: # optional, default is ${{ github.head_ref || github.ref }}
    # GitHub API Token
    github_token: # optional, default is ${{ github.token }}
    # Additional parameters for AST scan
    additional_params: # optional, default is 
    # Repository name for PR decoration
    repo_name: # optional, default is ${{ github.event.repository.name }}
    # Organization name to create the Pr comment
    namespace: # optional, default is ${{ github.repository_owner }}
    # Pr Number of the pull request that needs the decoration
    pr_number: # optional, default is ${{ github.event.number }}
    
